repos:
- repo: local
  hooks:
  - id: generate-commit-message
    name: Generate Commit Message
    entry: ./script.sh
    language: python
    additional_dependencies: ['openai==0.28.1', 'python-dotenv==0.19.0']
    stages: [prepare-commit-msg]
